DIVE_IN_BUTTON = "//a[@aria-controls='home-dive-in']"
AMOUNT_INFO = "//div[@class='tuck-7']//div[@class='tuck-5']//span[contains(@class, 'h1')]"
AGENCY_NAME_INFO = "//div[@class='tuck-7']//div[@class='tuck-5']//span[contains(@class, 'h4')]"
AGENCY_LINK = lambda agency_name: f"//div[@class='tuck-7']//div[@class='tuck-5']//span[contains(@class, 'h4') and text()[1]='{agency_name}']"
INVESTMENTS_TABLE = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']"
UII_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'sorting_2')]//a"
SECOND_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'select-filter') and position()=2]"
THIRD_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'left') and position()=3]"
FOURTH_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'right') and position()=4]"
FIFTH_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'select-filter') and position()=5]"
SIXTH_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'center') and position()=6]"
SEVENTH_COLUMN = "//table[contains(@class, 'dataTable') and @aria-describedby='investments-table-object_info']//tbody//td[contains(@class, 'center') and position()=7]"
